
import React, { useState, useEffect, useRef, useMemo } from 'react';
import { CodingProblem, RunResult, TestResult } from '../types';
import { CodingService } from '../services/codingService';
import { Avatar } from './Avatar';

interface CodingWorkspaceProps {
  onBack: () => void;
  initialProblem?: CodingProblem | null; // Optional prop for when problem is generated by AI
  isTalking: boolean;
  isActive: boolean;
  onCodeChange?: (code: string) => void;
}

// Internal CodeEditor Component for Highlighting
const CodeEditor: React.FC<{
  code: string;
  language: string;
  onChange: (val: string) => void;
}> = ({ code, language, onChange }) => {
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const preRef = useRef<HTMLPreElement>(null);

  // Sync scroll between textarea and pre
  const handleScroll = () => {
    if (textareaRef.current && preRef.current) {
      preRef.current.scrollTop = textareaRef.current.scrollTop;
      preRef.current.scrollLeft = textareaRef.current.scrollLeft;
    }
  };

  // Perform highlighting safely
  const highlightedCode = useMemo(() => {
    if (typeof window !== 'undefined' && (window as any).Prism) {
      const Prism = (window as any).Prism;
      const grammar = Prism.languages[language] || Prism.languages.javascript;
      return Prism.highlight(code, grammar, language);
    }
    // Fallback simple escape
    return code.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  }, [code, language]);

  return (
    <div className="relative flex-1 w-full h-full bg-[#1e1e1e] overflow-hidden group">
      {/* Background Syntax Highlighter */}
      <pre
        ref={preRef}
        aria-hidden="true"
        className={`absolute inset-0 m-0 p-4 font-mono text-sm leading-6 pointer-events-none overflow-hidden`}
        style={{ fontFamily: 'Menlo, Monaco, Consolas, "Courier New", monospace' }}
      >
        <code
          className={`language-${language}`}
          dangerouslySetInnerHTML={{ __html: highlightedCode + '<br />' }} 
        />
      </pre>

      {/* Foreground Interactive Editor */}
      <textarea
        ref={textareaRef}
        value={code}
        onChange={(e) => onChange(e.target.value)}
        onScroll={handleScroll}
        spellCheck={false}
        autoCapitalize="off"
        autoComplete="off"
        className="absolute inset-0 w-full h-full p-4 font-mono text-sm leading-6 bg-transparent text-transparent caret-white resize-none focus:outline-none"
        style={{ 
          fontFamily: 'Menlo, Monaco, Consolas, "Courier New", monospace',
          // Ensure text color is transparent so the highlighted code shows through
          WebkitTextFillColor: 'transparent',
          color: 'transparent'
        }}
      />
    </div>
  );
};

// Collapsible Test Result Item
const TestResultItem: React.FC<{ result: TestResult; index: number }> = ({ result, index }) => {
  // Auto-expand if failed, collapse if passed
  const [isOpen, setIsOpen] = useState(!result.passed);

  return (
    <div className={`text-xs rounded border transition-colors duration-200 overflow-hidden ${result.passed ? 'bg-green-900/10 border-green-900/30' : 'bg-red-900/10 border-red-900/30'}`}>
      <button 
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex items-center justify-between p-3 hover:bg-white/5 transition-colors focus:outline-none"
      >
        <div className="flex items-center gap-2">
           <svg 
            className={`w-3 h-3 transition-transform duration-200 ${isOpen ? 'rotate-90' : 'rotate-0'} ${result.passed ? 'text-green-500' : 'text-red-500'}`} 
            fill="none" viewBox="0 0 24 24" stroke="currentColor"
           >
             <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
           </svg>
           <span className={`font-bold ${result.passed ? 'text-green-500' : 'text-red-500'}`}>Test Case #{index + 1}</span>
        </div>
        <span className="text-gray-500 font-mono">{result.passed ? 'PASS' : 'FAIL'}</span>
      </button>
      
      {isOpen && (
        <div className="p-3 pt-0 border-t border-white/5 bg-black/20">
           <div className="grid grid-cols-[80px_1fr] gap-x-2 gap-y-1 font-mono text-gray-400 mt-2">
              <span>Input:</span> <span className="text-gray-300 break-all">{result.input}</span>
              <span>Expected:</span> <span className="text-gray-300 break-all">{result.expected}</span>
              {!result.passed && (
                <>
                  <span className="text-red-400">Actual:</span> <span className="text-red-300 break-all">{result.actual}</span>
                </>
              )}
           </div>
        </div>
      )}
    </div>
  );
};

export const CodingWorkspace: React.FC<CodingWorkspaceProps> = ({ onBack, initialProblem, isTalking, isActive, onCodeChange }) => {
  const [problem, setProblem] = useState<CodingProblem | null>(initialProblem || null);
  const [code, setCode] = useState('');
  const [language, setLanguage] = useState<'javascript' | 'python'>('javascript');
  const [result, setResult] = useState<RunResult | null>(null);
  const [loading, setLoading] = useState(!initialProblem);
  const [running, setRunning] = useState(false);
  const [isConsoleOpen, setIsConsoleOpen] = useState(true);
  
  const codingService = useMemo(() => new CodingService(), []);

  useEffect(() => {
    // If we were passed an initial problem, use it and don't load a new one
    if (initialProblem) {
      setProblem(initialProblem);
      setCode(initialProblem.functionSignature.javascript);
      setLanguage('javascript');
      setLoading(false);
      // Notify initial code
      if (onCodeChange) onCodeChange(initialProblem.functionSignature.javascript);
    } else {
      loadProblem();
    }
  }, [initialProblem]);

  const loadProblem = async () => {
    setLoading(true);
    setResult(null);
    try {
      const p = await codingService.generateProblem();
      setProblem(p);
      setCode(p.functionSignature.javascript);
      setLanguage('javascript');
      if (onCodeChange) onCodeChange(p.functionSignature.javascript);
    } catch (e) {
      console.error(e);
      alert("Failed to generate problem. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleLanguageChange = (lang: 'javascript' | 'python') => {
    setLanguage(lang);
    if (problem) {
      const newCode = problem.functionSignature[lang];
      setCode(newCode);
      if (onCodeChange) onCodeChange(newCode);
    }
  };

  const handleCodeChange = (newCode: string) => {
    setCode(newCode);
    if (onCodeChange) onCodeChange(newCode);
  };

  const handleRun = async () => {
    if (!problem) return;
    setRunning(true);
    setResult(null);
    setIsConsoleOpen(true);
    try {
      const res = await codingService.evaluateCode(code, language, problem);
      setResult(res);
    } catch (e) {
      console.error(e);
      alert("Error evaluating code.");
    } finally {
      setRunning(false);
    }
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center h-[500px] text-gray-400 gap-4">
        <div className="w-8 h-8 border-4 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
        <p>Generating Coding Challenge with Gemini...</p>
      </div>
    );
  }

  if (!problem) return null;

  return (
    <div className="flex flex-col gap-6 h-full">
      {/* Problem Definition & Avatar Header */}
      <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6 shadow-xl shrink-0">
        <div className="flex gap-6">
          {/* Left: Text Content */}
          <div className="flex-1">
            <div className="flex justify-between items-start mb-4">
              <div>
                 <h2 className="text-xl font-bold text-white mb-1">{problem.title}</h2>
                 <div className="flex items-center gap-2">
                    <span className="inline-block px-2 py-0.5 rounded text-[10px] font-mono bg-green-900/50 text-green-400 border border-green-800">
                      {problem.difficulty}
                    </span>
                    <span className="text-xs text-gray-500 font-mono">
                       Function: <span className="text-gray-300">{problem.entryFunctionName}</span>
                    </span>
                 </div>
              </div>
              <button onClick={onBack} className="text-sm text-gray-500 hover:text-white transition-colors">
                Close
              </button>
            </div>
            <p className="text-gray-300 text-sm leading-relaxed whitespace-pre-wrap font-sans">
              {problem.description}
            </p>
          </div>

          {/* Right: Mini Avatar */}
          <div className="w-56 h-32 shrink-0 rounded-xl overflow-hidden border border-gray-700 shadow-lg bg-black hidden md:block">
            <Avatar isTalking={isTalking} isActive={isActive} />
          </div>
        </div>
      </div>

      {/* Editor & Controls */}
      <div className="flex-1 flex flex-col bg-[#1e1e1e] border border-gray-800 rounded-2xl overflow-hidden shadow-xl min-h-[400px]">
        {/* Toolbar */}
        <div className="bg-[#2d2d2d] border-b border-gray-700 p-3 flex justify-between items-center shrink-0">
          <div className="flex items-center gap-3">
            <span className="text-xs font-mono text-gray-400 uppercase tracking-wider">Language:</span>
            <div className="relative">
              <select 
                value={language}
                onChange={(e) => handleLanguageChange(e.target.value as 'javascript' | 'python')}
                className="appearance-none bg-[#3c3c3c] text-white text-xs font-medium pl-3 pr-8 py-1.5 rounded border border-gray-600 focus:outline-none focus:border-blue-500 hover:bg-[#4c4c4c] transition-colors cursor-pointer"
              >
                <option value="javascript">JavaScript</option>
                <option value="python">Python</option>
              </select>
              <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-400">
                <svg className="fill-current h-3 w-3" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
              </div>
            </div>
          </div>

          <button 
            onClick={handleRun}
            disabled={running}
            className={`flex items-center gap-2 px-4 py-1.5 rounded text-xs font-bold uppercase tracking-wide transition-all ${running ? 'bg-gray-700 text-gray-500 cursor-not-allowed' : 'bg-green-600 hover:bg-green-500 text-white shadow-lg shadow-green-900/20'}`}
          >
            {running ? (
              <>
               <div className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin"/>
               Running...
              </>
            ) : (
              <>
               <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 3l14 9-14 9V3z" /></svg>
               Run Code
              </>
            )}
          </button>
        </div>

        {/* Highlighted Editor */}
        <CodeEditor 
          code={code} 
          language={language} 
          onChange={handleCodeChange} 
        />

        {/* Collapsible Console */}
        <div className={`bg-[#0d1117] border-t border-gray-800 transition-all duration-300 flex flex-col ${isConsoleOpen ? 'h-[250px]' : 'h-[40px]'}`}>
          <button 
            onClick={() => setIsConsoleOpen(!isConsoleOpen)}
            className="flex items-center justify-between px-4 h-[40px] bg-[#161b22] hover:bg-[#1f242c] transition-colors cursor-pointer w-full focus:outline-none shrink-0"
          >
            <div className="flex items-center gap-2">
               <svg 
                  className={`w-4 h-4 text-gray-500 transition-transform duration-200 ${isConsoleOpen ? 'rotate-180' : ''}`} 
                  fill="none" viewBox="0 0 24 24" stroke="currentColor"
               >
                 <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
               </svg>
               <span className="text-[10px] uppercase tracking-widest text-gray-500 font-mono">Output Console</span>
            </div>
            
            {result && !running && (
              <span className={`text-xs font-mono ${result.passedCount === result.totalCount ? 'text-green-500' : 'text-red-500'}`}>
                {result.passedCount}/{result.totalCount} Tests Passed
              </span>
            )}
          </button>

          <div className="overflow-y-auto p-4 flex-1">
            
            {!result && !running && <p className="text-gray-600 text-xs italic">Click run to execute on remote server (Judge0).</p>}
            
            {result?.error && (
              <div className="bg-red-900/20 border border-red-900/50 p-3 rounded">
                 <h4 className="text-red-400 text-xs font-bold mb-1">Execution Error</h4>
                 <pre className="text-red-300 text-xs font-mono whitespace-pre-wrap">{result.error}</pre>
              </div>
            )}

            {result && !result.error && (
              <div className="space-y-3">
                <div className="flex items-center gap-2 mb-4">
                  <div className={`text-lg font-bold ${result.passedCount === result.totalCount ? 'text-green-400' : 'text-red-400'}`}>
                    {result.passedCount}/{result.totalCount} Passed
                  </div>
                  {result.passedCount === result.totalCount && (
                    <span className="text-xs bg-green-900/30 text-green-400 px-2 py-0.5 rounded border border-green-900">
                      All Tests Passed
                    </span>
                  )}
                </div>

                <div className="grid grid-cols-1 gap-2">
                  {result.results.map((r, i) => (
                    <TestResultItem key={i} result={r} index={i} />
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
